name: Pipeline
on:
  push:
    branches:
      [ 'main' ]
  pull_request:
    branches:
      [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports: [ '5432:5432' ]

    steps:
      - name: Instalar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Copia os arquivos do repositório
        uses: actions/checkout@v4

      - name: Instalar poetry
        run: curl -sSL https://install.python-poetry.org | python3 - && export PATH="/root/.local/bin:$PATH"

      - name: Instalar dependências
        run: poetry install --with dev --no-interaction --no-root

      - name: Copiar o .env
        run: cp contrib/env-sample .env

      - name: Rodar o flake8
        run: poetry run flake8

      - name: Rodar os testes
        run: poetry run pyteste --cov=api

#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    needs: test
#    steps:
#      - uses: actions/checkout@v4
#      - uses: superfly/flyctl-actions/setup-flyctl@master
#      - run: flyctl deploy --remote-only
#        env:
#          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
